version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Install Heroku CLI (If not installed)
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: Install heroku plugin
          command: heroku plugins:install heroku-repo
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              heroku repo:purge_cache -a mathspace-staging-website &&
              heroku repo:reset -a mathspace-staging-website &&
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/mathspace-staging-website.git
            fi
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              heroku repo:purge_cache -a mathspace-production-website &&
              heroku repo:reset -a mathspace-production-website &&
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/mathspace-production-website.git production:master
            fi

workflows:
  version: 2
  build_website:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - production
